# Generated by Django 4.1 on 2023-10-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=100)),
                ('image_size', models.IntegerField()),
                ('image_url', models.URLField()),
                ('image_format', models.CharField(max_length=100)),
                ('image_compressed', models.ImageField(upload_to='images/')),
                ('image_compressed_size', models.IntegerField()),
                ('image_compressed_url', models.URLField()),
                ('image_compressed_format', models.CharField(max_length=100)),
                ('image_compression_ratio', models.FloatField()),
                ('image_compression_time', models.FloatField()),
                ('image_compression_date', models.DateTimeField(auto_now_add=True)),
                ('image_compression_status', models.BooleanField(default=False)),
            ],
        ),
    ]
