# Generated by Django 4.1 on 2023-10-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='image_compression_psnr',
            field=models.FloatField(null=True),
        ),
    ]
